// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package zipkin_graphql

type Pagination struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

type Span struct {
	URL string `json:"url"`
}
